# 資料庫連線設定
jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/toiukha?serverTimezone=Asia/Taipei
jdbc.user=root
jdbc.password=necz1X23c4V

# Hibernate 設定
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update 